modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
modId = "lootbeams"
version = "1.20.1"
logoFile = "banner.png"
authors = "Clefal"
displayName = "LootBeams: Refork"
displayTest="IGNORE_ALL_VERSION"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/loot-beams-refork"
description = '''
Loot items, guided by light!
'''
[[dependencies.lootbeams]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.lootbeams]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.lootbeams]]
modId = "apotheosis"
mandatory = false
versionRange = "[7.2.0,)"
ordering = "AFTER"
side = "CLIENT"
[[dependencies.lootbeams]]
modId = "mmorpg"
mandatory = false
versionRange = "[5.9.0,)"
ordering = "AFTER"
side = "CLIENT"
